name: condition
on: [push]
jobs:
  conditions-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World"
      
      - name: trigger PROD deploy
        if: github.ref == 'refs/heads/main'
        run: echo "deploy to PROD"

      # this part will skip. it's not main branch
      - name: trigger DEV deploy
        if: github.ref == 'refs/heads/feature-*'
        run: echo "deploy to DEV"