name: Parallel
on: [push] 
jobs: 
  jobs-1: 
    runs-on: ubuntu-latest # where to run
    steps:
      - name: Print Hello World 1
        run: echo "Hello, World 1"

  jobs-2: 
    needs: jobs-1 # this will run after the jobs-1 completions
    runs-on: ubuntu-latest # where to run
    steps:
      - name: Print Hello World 2
        run: echo "Hello, World 2"

  jobs-3: 
    runs-on: ubuntu-latest # where to run
    steps:
      - name: Print Hello World 3
        run: echo "Hello, World 3"

  jobs-4: 
    runs-on: ubuntu-latest # where to run
    steps:
      - name: Print Hello World 4
        run: echo "Hello, World 4"